<?php
namespace EfikaTest\EventManager;

use Efika\EventManager\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-29 at 15:42:32.
 */
class ExceptionTest extends \PHPUnit_Framework_TestCase
{

    public function testThrowException(){

        try {
            throw new Exception('Test Error');
        } catch (Exception $e){
            $this->assertInstanceOf('\Exception',$e);
            $this->assertInstanceOf('Efika\EventManager\Exception',$e);
        }
    }
}
